# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
  
- task: JavaToolInstaller@0
  inputs:
      versionSpec: '11'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    #javaHomeOption: 'JDKVersion'
    #jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/target/cucumber.html'
    goals: 'clean verify -P acceptanceTests -e -X'

- task: NodeTool@0
  displayName: 'Install Node 12.x'
  inputs:
    versionSpec: 12.x
    
- task: PublishCucumberReport@1
  displayName: 'Publish Cucumber Report'
  inputs:
          jsonDir: ./target/cucumber
          outputPath: ./results/cucumber
          metadata: |
            {
              "ApplicationUrl": "$(App.Url)"
            }
          name: 'Functional Tests'
          title: API
